spring:
  application:
    name: account-manage-service

  datasource:
    url: jdbc:mysql://localhost:3306/artar_database?serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 30001

account:
    password: zhang1998

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml